[package]
name = "aves"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.15.1"
bevy_mod_raycast = "0.18.0"
once_cell = "1.20.2"

[profile.dev]
opt-level = 1

# Enable a large amount of optimization in the dev profile for dependencies.
[profile.dev.package."*"]
opt-level = 3

